### ISSUE TITLE
Mutual recursion is not supported

### ISSUE THREAD

**Issue by 7sharp9** [jet/falanx#139]
Given the following proto definition:
```
// Test that mutual recursion works.
message TestMutualRecursionA {
  TestMutualRecursionB bb = 1;
}

message TestMutualRecursionB {
  TestMutualRecursionA a = 1;
  int32 optional_int32 = 2;
}
```
The following error results as neither type can be processed by the other, not sure how to fix this due to the way types are processed by providedtypes.

```
type 'TestMutualRecursionA' was not yet added as a member to a declaring type, stacktrace =    at System.Environment.get_StackTrace()
   at ProviderImplementation.ProvidedTypes.ProvidedTypeDefinition.get_Assembly() in /Users/dave.thomas/Documents/GitHub/falanx/paket-files/7sharp9/FSharp.TypeProviders.SDK/src/ProvidedTypes.fs:line 1508
   at Falanx.Machinery.Reflection.Impl.tryFindCompilationMappingAttributeFromType(Type typ) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Reflection.fs:line 52
   at Falanx.Machinery.Reflection.Impl.tryFindSourceConstructFlagsOfType(Type typ) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Reflection.fs:line 60
   at Falanx.Machinery.Reflection.Impl.isExceptionRepr(Type typ, BindingFlags bindingFlags) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Reflection.fs:line 67
   at Falanx.Machinery.Reflection.Impl.getTypeOfReprType(Type typ, BindingFlags bindingFlags) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Reflection.fs:line 118
   at Falanx.Machinery.Reflection.FSharpTypeSafe.IsFunction(Type typ) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Reflection.fs:line 256
   at Falanx.Machinery.Utils.sysTypeToSynType(range range, Type t, FSharpSet`1 knownNamespaces, FSharpOption`1 ommitEnclosingType) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Utils.fs:line 206
   at Falanx.Machinery.Utils.synParams@213.Invoke(Type arg) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Utils.fs:line 213
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Falanx.Machinery.Utils.sysTypeToSynType(range range, Type t, FSharpSet`1 knownNamespaces, FSharpOption`1 ommitEnclosingType) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/Utils.fs:line 213
   at <StartupCode$Falanx-Machinery>.$QuotationToAst.exprToAst@23.Invoke(FSharpExpr expr) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/QuotationToAst.fs:line 64
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at <StartupCode$Falanx-Machinery>.$QuotationToAst.exprToAst@23.Invoke(FSharpExpr expr) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/QuotationToAst.fs:line 273
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at <StartupCode$Falanx-Machinery>.$QuotationToAst.exprToAst@23.Invoke(FSharpExpr expr) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/QuotationToAst.fs:line 273
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at <StartupCode$Falanx-Machinery>.$QuotationToAst.exprToAst@23.Invoke(FSharpExpr expr) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/QuotationToAst.fs:line 273
   at Falanx.Machinery.Quotations.ToAst(FSharpExpr expr, FSharpOption`1 ommitEnclosingType, FSharpOption`1 knownNamespaces) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Machinery/QuotationToAst.fs:line 497
   at Falanx.Proto.Core.JsonCodec.createJsonObjCodec(TypeDescriptor typeDescriptor) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Core/JsonCodec/Codec.fs:line 429
   at Falanx.Proto.Generator.TypeGeneration.createType@237-6.Invoke(Codec codec) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Generator/TypeGeneration.fs:line 262
   at Microsoft.FSharp.Collections.SetTreeModule.iter[a](FSharpFunc`2 f, SetTree`1 t)
   at Falanx.Proto.Generator.TypeGeneration.createType(ProvidedTypeDefinition container, String scope, FSharpMap`2 lookup, FSharpSet`1 codecs, ProtoMessage message) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Generator/TypeGeneration.fs:line 235
   at Falanx.Proto.Generator.Proto.generatedTypes@88-1.Invoke(ProtoMessage message) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Generator/CreateProto.fs:line 88
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Falanx.Proto.Generator.Proto.createProvidedTypes(String protoDef, String defaultnamespace, FSharpSet`1 codecs) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Generator/CreateProto.fs:line 86
   at Falanx.Proto.Generator.Proto.createFSharpDefinitions(String protoDef, String outputFile, String defaultnamespace, FSharpSet`1 codecs) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Proto.Generator/CreateProto.fs:line 117
   at Falanx.Generator.main.main(String[] argv) in /Users/dave.thomas/Documents/GitHub/falanx/src/Falanx.Tool/Program.fs:line 43
```

**Comment by 7sharp9** [comment]
Spoke with @gusty, in short we need to use the new API to get this to work.  A fair bit of work is involved so Ive put this on the back burner until someone wants recursive proto types.
