### ISSUE TITLE
In a proto message a map followed by a primitive causes an exception

### ISSUE THREAD

**Issue by 7sharp9** [jet/falanx#152]
```proto
syntax = "proto3";

message SomeMessage {
    int64 id = 1;
}

message SomeMessageWithMap {
    int64 aField = 1;
    map<string, SomeMessage> some_map = 2;
    string anotherField = 3;
    
}
```

```
An error occurred while generating type for message SomeMessageWithMap: System.ArgumentException: Type mismatch when building 'recd': incorrect argument type for an F# record. Expected 'Microsoft.FSharp.Core.FSharpOption`1[System.String]', but received type 'System.Collections.Generic.Dictionary`2[System.String,test.TypeContainer+SomeMessage]'.
Parameter name: receivedType
   at Microsoft.FSharp.Quotations.PatternsModule.checkTypesSR[a](Type expectedType, Type receivedType, a name, String threeHoleSR)
   at Microsoft.FSharp.Quotations.PatternsModule.mkNewRecord@771.Invoke(PropertyInfo minfo, FSharpExpr a)
   at Microsoft.FSharp.Collections.ListModule.loop@192-27[T1,T2](FSharpFunc`3 f, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.Iterate2[T1,T2](FSharpFunc`2 action, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Quotations.PatternsModule.mkNewRecord(Type ty, FSharpList`1 args)
   at Falanx.Proto.Core.JsonCodec.createLambdaRecord(TypeDescriptor typeDescriptor) in falanx/src/Falanx.Proto.Core/JsonCodec/Codec.fs:line 53
   at Falanx.Proto.Core.JsonCodec.createJsonObjCodec(TypeDescriptor typeDescriptor) in falanx/src/Falanx.Proto.Core/JsonCodec/Codec.fs:line 432
   at Falanx.Proto.Generator.TypeGeneration.createType@263-6.Invoke(Codec codec) in falanx/src/Falanx.Proto.Generator/TypeGeneration.fs:line 289
   at Microsoft.FSharp.Collections.SetTreeModule.iter[a](FSharpFunc`2 f, SetTree`1 t)
   at Falanx.Proto.Generator.TypeGeneration.createType(ProvidedTypeDefinition container, String scope, FSharpMap`2 lookup, FSharpSet`1 codecs, ProtoMessage message) in falanx/src/Falanx.Proto.Generator/TypeGeneration.fs:line 261
```

**Comment by 7sharp9** [comment]
Fixed by #150
