### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#70]
**Describe the bug**
`dotnet test Falanx.sln` fail

**To Reproduce**
`dotnet test Falanx.sln` produce error (see also environment):
```
System.IO.FileNotFoundException: Unable to find tests for C:\Users\vadym.chekan\source\repos\falanx_upstream\test\Falanx.IntegrationTests\bin\Debug\netcoreapp2.1\Falanx.IntegrationTests.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```

**Environement (please complete the following information):**
 - OS: windows; mingw64 bash 
 - Framework dotnetcore-2.1

**Comment by 7sharp9** [comment]
The command that @enricosada told me to use is:
```
dotnet test -v n build.proj
```
Also I believe that
```
dotnet pack build.proj -v n
```
Has to be ran first.  The solution file could do with being moved as theres a limitation in dotnet where it cant exist in the same directory as another msbuild file (_its easily confused_)
